# Generated by Django 4.2.6 on 2023-11-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0004_student_age_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
