# Generated by Django 4.2.6 on 2023-11-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0005_remove_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
    ]
