# Generated by Django 4.2.6 on 2023-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0006_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
