# Generated by Django 4.2.6 on 2023-11-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0008_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(max_length=20),
        ),
    ]
